package core

import "github.com/nikkolasg/dsign/key"

// Store is an interface that allows to save and load cryptograhic materials as
// well as signatures.
type Store interface {
	KeyStore
	SignatureStore
}

// KeyStore is an interface that allows to retrieve and save longterm key material
type KeyStore interface {
	LongtermKey() (*key.Private, error)
	LongtermShare() (*key.SharedPrivate, error)
	SaveLongterm(*key.SharedPrivate) error
}

// SignatureStore is an interface that allows to store the distributed
// signatures generated by dsign.
type SignatureStore interface {
	SaveSignature()
}
